#!/sbin/openrc-run

name=$RC_SVCNAME
command="/bin/ash"
command_args="/home/piped/start.sh"
command_user="piped"
directory="/home/piped"

output_log="/var/log/$RC_SVCNAME/piped.log"
error_log="/var/log/$RC_SVCNAME/error.log"

pidfile="/run/$RC_SVCNAME/$RC_SVCNAME.pid"
command_background="yes"

depend() {
        need net
}

start_pre() {
        checkpath --directory --owner $command_user:$command_user --mode 0775 \
                /run/$RC_SVCNAME /var/log/$RC_SVCNAME
}
